Repository Algo1886/Algo_BE, pull requests merged in 2025-09, with the labels that each got.

#24 [FEAT] 유형 분포 조회 API 구현
  src/main/java/com/teamalgo/algo/controller/StatsController.java
  src/main/java/com/teamalgo/algo/dto/response/CategoryStatsResponse.java
  src/main/java/com/teamalgo/algo/repository/RecordCategoryRepository.java
  src/main/java/com/teamalgo/algo/service/stats/CategoryStatsService.java
Labels: feat

#27 [FEAT] 이미지 업로드 API 구현
  build.gradle
  src/main/java/com/teamalgo/algo/controller/ImageController.java
  src/main/java/com/teamalgo/algo/dto/response/ImageUrlResponse.java
  src/main/java/com/teamalgo/algo/global/common/code/ErrorCode.java
  src/main/java/com/teamalgo/algo/global/config/S3Config.java
  src/main/java/com/teamalgo/algo/service/image/ImageService.java
  src/main/resources/application.yml
Labels: feat

#31 [FIX] Record 삭제 시 ReviewLog/Bookmark 삭제 누락 문제 해결
  src/main/java/com/teamalgo/algo/domain/record/Record.java
Labels: fix

#32 [FEAT] 레코드/북마크/아이디어 조회 정책 개선 (draft·비공개 처리)
  src/main/java/com/teamalgo/algo/controller/RecordController.java
  src/main/java/com/teamalgo/algo/repository/BookmarkRepository.java
  src/main/java/com/teamalgo/algo/repository/RecordCoreIdeaRepository.java
  src/main/java/com/teamalgo/algo/repository/RecordRepository.java
  src/main/java/com/teamalgo/algo/service/record/BookmarkService.java
  src/main/java/com/teamalgo/algo/service/record/CoreIdeaService.java
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: feat

#34 [FIX] 레코드 생성/수정 시 유효성 검증 강화
  src/main/java/com/teamalgo/algo/controller/RecordController.java
  src/main/java/com/teamalgo/algo/dto/RecordCodeDTO.java
  src/main/java/com/teamalgo/algo/dto/RecordStepDTO.java
  src/main/java/com/teamalgo/algo/dto/request/RecordCreateRequest.java
  src/main/java/com/teamalgo/algo/dto/request/RecordUpdateRequest.java
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: fix

#35 [REFACTOR] UserResponse streak 응답 처리 수정
  src/main/java/com/teamalgo/algo/dto/response/UserResponse.java
  src/main/java/com/teamalgo/algo/service/stats/StatsService.java
  src/main/java/com/teamalgo/algo/service/user/UserService.java
Labels: refactor

#44 [FIX] 임시저장 기록은 통계 반영 대상에서 제외
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: fix

#49 [FIX] 이미지 업로드 500 에러 수정
  src/main/java/com/teamalgo/algo/global/common/code/ErrorCode.java
  src/main/java/com/teamalgo/algo/service/image/ImageService.java
  src/main/resources/application.yml
Labels: fix

#56 [FIX] 레코드 search 로직 수정 & 비로그인 쿼리 적용
  src/main/java/com/teamalgo/algo/controller/RecordController.java
  src/main/java/com/teamalgo/algo/repository/RecordRepository.java
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: fix

#59 [FEAT] 문제 유형 조회 API 추가 & categoryIds 기반 매핑으로 변
  src/main/java/com/teamalgo/algo/controller/CategoryController.java
  src/main/java/com/teamalgo/algo/domain/category/Category.java
  src/main/java/com/teamalgo/algo/dto/CategoryDTO.java
  src/main/java/com/teamalgo/algo/dto/request/RecordCreateRequest.java
  src/main/java/com/teamalgo/algo/dto/request/RecordUpdateRequest.java
  src/main/java/com/teamalgo/algo/service/record/CategoryService.java
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: feat

#61 [REFACTOR] 유형 조회 id 순으로 정렬
  src/main/java/com/teamalgo/algo/repository/CategoryRepository.java
  src/main/java/com/teamalgo/algo/service/record/CategoryService.java
Labels: refactor

#62 fix: 복습 추천 조회 시 draft 노출 문제 수정
  src/main/java/com/teamalgo/algo/repository/RecordRepository.java
  src/main/java/com/teamalgo/algo/service/record/ReviewService.java
Labels: fix

#65 [REFACTOR] 환경별 application.yml 분리
  .github/workflows/deploy.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: refactor

#66 [FEAT] 사용자 정보 수정 응답에 스트릭 추가
  src/main/java/com/teamalgo/algo/dto/response/UserResponse.java
  src/main/java/com/teamalgo/algo/service/user/UserService.java
Labels: feat

#67 [REFACTOR] 기록 등록 & 수정 DTO 필드명 categories로 변경
  src/main/java/com/teamalgo/algo/dto/request/RecordCreateRequest.java
  src/main/java/com/teamalgo/algo/dto/request/RecordUpdateRequest.java
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: refactor

#70 [FIX] 기록 수정 시 카테고리 중복 삽입으로 인한 unique 제약 오류 해결
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: fix

#71 [REFACTOR] 기록 조회 응답 categories 형식 변경
  src/main/java/com/teamalgo/algo/dto/response/RecordResponse.java
  src/main/java/com/teamalgo/algo/service/record/RecordService.java
Labels: refactor
